---
abstract: 'a simple policy enforcing strict version formatting'
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Policy-logicLAB-RequireVersionFormat
provides:
  Perl::Critic::Policy::logicLAB::RequireVersionFormat:
    file: lib/Perl/Critic/Policy/logicLAB/RequireVersionFormat.pm
    version: '0.07'
requires:
  List::MoreUtils: '0'
  Perl::Critic: '1.03'
  Perl::Critic::Utils: '0'
  Test::Perl::Critic: '0'
  perl: v5.8.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-Policy-logicLAB-Prohibit-RequireVersionFormat
  homepage: http://logiclab.jira.com/wiki/display/PCPMRVF/Home
  license: http://opensource.org/licenses/artistic-license.php
  projectChangelog: http://logiclab.jira.com/browse/PCPMRVF#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/PCPMRVF
  projectWiki: http://logiclab.jira.com/wiki/display/PCPMRVF/Home
  repository: https://github.com/jonasbn/pcpmrvf
version: '0.07'
