---
abstract: 'a simple policy enforcing strict version formatting'
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-RequireVersionFormat
provides:
  Perl::Critic::Policy::logicLAB::RequireVersionFormat:
    file: lib/Perl/Critic/Policy/logicLAB/RequireVersionFormat.pm
    version: 0.03
requires:
  List::MoreUtils: 0
  Perl::Critic: 1.03
  Perl::Critic::Utils: 0
  Test::Perl::Critic: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCPMRVF#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCPMRVF
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCPMRVF/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-logicLAB-Prohibit-RequireVersionFormat
  homepage: http://logiclab.jira.com/wiki/display/PCPMRVF/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/PCPMRVF
version: 0.03
